[package]
name = "Warren"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
actix-identity = "0.3.1"
tera = "1.5.0"
serde = "1.0"
clap = { version = "4.5.16", features = ["derive"] }
